spring:
  datasource:
    url: jdbc:mysql://localhost/starbuks?createDatabaseIfNotExist=true
    username: root
    password: Cibertec25
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true